//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomApp.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Credentials = new HashSet<Credential>();
            this.Points = new HashSet<Point>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
    
        public virtual ICollection<Credential> Credentials { get; set; }
        public virtual ICollection<Point> Points { get; set; }
    }
}
